### PR TITLE
Register commands with tagged services

### PR DESCRIPTION
**Pull request by osavchenko**
Make all commands as tagged services and automatically register them on container compilation

### CODE REVIEW

**Comment by osavchenko** [comment]
@SergiX44 Do think it makes sense to cover with `pestphp/pest` DI configuration here or should I do it with a simple PHPUnit test?

**Comment by SergiX44** [comment]
> @SergiX44 Do think it makes sense to cover with `pestphp/pest` DI configuration here or should I do it with a simple PHPUnit test?

Tests are written with pest so I would keep it in that way without mixing in phpunit. 

Other than this looks good I think, I'm still pretty much a newbie with Symfony.

**Comment by osavchenko** [comment]
> Tests are written with pest so I would keep it in that way without mixing in phpunit.

Ok, I'll cover new changes with unit tests.

> Other than this looks good I think, I'm still pretty much a newbie with Symfony.

Then let's learn from each other: I'll explain my code and during this, I'll learn better how the library works :)

When I saw the directory structure [here](https://nutgram.dev/docs/configuration/symfony/#servicesyaml-configuration) I thought that it was something that was predefined by the bundle for future usage. Then I start looking for a way how I can add the commands to the bot and found that it can be done with the [registerCommand](https://nutgram.dev/docs/usage/handlers#registercommand). So, my idea is to register all application commands (classes that extend the `SergiX44\Nutgram\Handlers\Type\Command` class) as tagged services during the container compilation and then I grab all the tagged services and push them to the bot instance with the `registerCommand()` method. 

As I understand, the final step is to call the `registerMyCommands()` method but I didn't apply it here because it won't allow any next bot configuration manipulations, right?

**Comment by SergiX44** [comment]
> When I saw the directory structure [here](https://nutgram.dev/docs/configuration/symfony/#servicesyaml-configuration) I thought that it was something that was predefined by the bundle for future usage. Then I start looking for a way how I can add the commands to the bot and found that it can be done with the [registerCommand](https://nutgram.dev/docs/usage/handlers#registercommand). 

So, that is done so the service containter inside Nutgram will be able to instantiate your classes (handlers, commands, conversations, etc) by himself and call them when processing updates; thats why that configuration, and why we are passing the Symfony container to Nutgram (inside, it will be set as a delegator https://github.com/nutgram/nutgram/blob/master/src/Nutgram.php#L100)

> As I understand, the final step is to call the `registerMyCommands()` method but I didn't apply it here because it won't allow any next bot configuration manipulations, right?

Actually no, that should be done (by the dev) when registering the commands for the first time, and every time you add/remove/change scope or description of a command. The `registerMyCommands()` is just an handy method to take all the registered commands in the current instance and issue a `setMyCommand` call to Telegram (https://core.telegram.org/bots/api#setmycommands) without having to create that call by yourself

**Comment by osavchenko** [comment]
> So, that is done so the service containter inside Nutgram will be able to instantiate your classes (handlers, commands, conversations, etc) by himself

But could you please describe how it happens? I didn't find anything in the documentation or in the code that allows you to automatically register commands and other things. I created the directory structure as it was described in the doc but my commands weren't registered automatically. From what I understand you had to manually call the `registerCommand()` for it.

Regarding `registerMyCommands()` -- thank you for the explanation

**Comment by SergiX44** [comment]
> 

Yes, your command are not registered automatically, you should register and define all your mappings inside the config/telegram.php file. The changes described in the documentation is for define everything inside the Telegram folder as a non shared service, so the Nutgram service container can delegate the instantiation to the Symfony one

**Comment by osavchenko** [comment]
My idea was to allow registering it automatically but I worked a bit more with your bundle and lib itself and noticed that it would be hard to do this way I presented in the PR because only command handlers have their own "main class" (`Command`). In the end, I want to develop this idea to make it configurable with Symfony instruments but maybe in another way that I purposed here

**Pull request closed without merging**
